name:                pyvobot
version:             0.1.0.0
github:              "honzajavorek/pyvo_bot"
license:             MIT
author:              "Honza Javorek"
maintainer:          "mail@honzajavorek.cz"
copyright:           "2019 Honza Javorek"

extra-source-files:
- LICENSE
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/honzajavorek/pyvo_bot#readme>

dependencies:
- base >= 4.7 && < 5
- wreq
- lens
- text
- time
- bytestring

library:
  source-dirs: src

executables:
  pyvo_bot:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pyvobot

tests:
  pyvo_bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pyvobot
