version: 2.1
jobs:
  send:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Install executable
          command: stack --no-terminal install
      - run:
          name: Run
          command: pyvo_bot Honza  # needs TELEGRAM_API_KEY set
workflows:
  version: 2
  default:
    jobs:
      - send
  daily:
    jobs:
      - send
    triggers:
      - schedule:
          cron: "0 10 * * *"
          filters:
            branches:
              only:
                - master
