version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Install executable
          command: stack --no-terminal install
      - run:
          name: Run
          command: pyvobot-exe Honza
